title: Aaryan Vira
description: Biomedical Engineer Portfolio
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache
  author:
  name: "Aaryan Vira"
  avatar: "/Screenshot 2026-07-26 at 1.40.21 PM.jpg"
  bio: "Biomedical Engineer"
